from irecordpackages.parser import (
    APPROVAL_ROUTING_MAPPING,
    REMIT_TO_CODE_MAPPING,
    BILLABLILITY_MAPPING,
    ACCOUNT_SEGMENT_MAPPING,
    LEGAL_COA_MAPPING,
    LEGAL_REQUESTER_MAPPING,
    SUPPLIER_MAPPING,
)


def reload_mapping_data():
    LEGAL_COA_MAPPING.load_data()
    APPROVAL_ROUTING_MAPPING.load_data()
    LEGAL_REQUESTER_MAPPING.load_data()
    REMIT_TO_CODE_MAPPING.load_data()
    SUPPLIER_MAPPING.load_data()
    BILLABLILITY_MAPPING.load_data()
    ACCOUNT_SEGMENT_MAPPING.load_data()
